### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Paul-Vasylenko** [Paul-Vasylenko/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Paul-Vasylenko-add** [comment]
Hey, it's me -- Michael Jackson! Do you remember me? The King of Pop Music, revolutioner in dance style, clothes  and the most popular and successful person in late 2000s and early 2010-th. I'm still alive but I don't won't anyone to know about it.

**Comment by Paul-Vasylenko** [comment]
not "anyone" but "too many people"
