### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Paul-Vasylenko** [Paul-Vasylenko/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Paul-Vasylenko-add** [comment]
My old website with merch - https://www.michaeljackson.com/
My instagram - https://www.instagram.com/michaeljackson/?hl=ru
My Facebook - https://www.facebook.com/michaeljackson
Check out my live perfomances on Youtube - https://www.youtube.com/michaeljackson
