### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Paul-Vasylenko** [Paul-Vasylenko/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Paul-Vasylenko-add** [comment]
EARLY YEARS

1958: Born Aug. 29 in Gary, Ind. He is the seventh child of Joseph and Katherine Esther Jackson.

1969: In Los Angeles, the Jackson 5 debut as Motown’s newest act.

In December, the group’s single “I Want You Back” hits No. 1 on the Billboard Top 40 Chart.

1970: Jackson 5 hits “ABC, “The Love You Save” and “I’ll Be There” all reach No. 1 on Billboard charts.

1972: First No. 1 solo hit “Ben,” a song about a movie rat.

1974: Introduces a dance step called the robot on “Soul Train.” The step sweeps the country.

1978: Played “The Scarecrow” in the movie musical “The Wiz,” alongside Diana Ross, Richard Pryor and Nipsey Russell.

1979: Jackson’s “Off the Wall” solo album catapults him to superstar status.

KING OF POP


1982: “Thriller” is released, eventually selling more than 100 million copies. It makes Jackson the biggest pop music star of the decade. The record becomes one of the best-selling albums of all time.

1983: “Beat It” reaches No. 1 on the charts.

“Billie Jean” also becomes a gigantic hit, and the influential video, featuring more of Jackson’s electric dancing, remains a landmark.

“Motown 25: Yesterday, Today, Forever,” airs on NBC. After a memorable performance by “The Jacksons,” Michael wows the crowd with a rendition of “Billie Jean,” which included the jaw-dropping moonwalk.

The high-concept, 13-minute “Thriller” video, directed by John Landis, becomes a huge sensation.

1984: Jackson’s hair catches on fire during filming of a Pepsi commercial.


1987: News reports say Jackson tries to buy the skeleton of the “Elephant Man.” The album “Bad” is released and sells more than 8 million copies.

1988: Michael Jackson donates $125,000 from a concert at the Palace of Auburn Hills, Mich., and some personal memorabilia to start off a fundraising drive to preserve and improve the Motown Historical Museum.

Releases “Moonwalk,” an autobiography.

PERSONAL TRIALS

1991: Releases “Dangerous” album, certified for 7 million in sales.

1993: In his first TV interview in 14 years, Jackson tells Oprah Winfrey that the change in his skin complexion is from a disorder called vitiligo.


A lawsuit claims that Jackson seduced and abused a 13-year-old boy.

1994: Settles the lawsuit with substantial payment to the plaintiff. Los Angeles and Santa Barbara district attorneys don’t file child molestation charges against him.

Marries Lisa Marie Presley, daughter of Elvis Presley.

1996: Presley files for divorce.

Jackson marries nurse Debbie Rowe.

1997: Rowe gives birth to son Prince Michael.


The Jackson 5 are inducted into the Rock and Roll Hall of Fame.

1998: Rowe gives birth to daughter Paris Michael Katherine.

DRAMA, DRAMA, DRAMA

2001: The “Invincible” album is released with a respectable 2.1 million copies sold, but only two minor hits.

2002: Third child, Prince Michael II is born.

2003: Faces charges of child molestation. Posts $3 million in bail and throws up the “V” sign, while standing on a black Suburban, before leaving the courthouse in Santa Maria, Calif.

2004: Jackson pleads not guilty to child molestation charges in January.

2005: In June, Jackson was acquitted of child molestation charges.

2009: Passed away.

2021: Still is a King of Music, style, kindness etc.
